TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -Os -g3
ASFLAGS = -g3

# object files

OBJS= stupid_delay.o  main.o UART.o esp8266.o simple_buffer.o $(STARTUP) $(HAL_COMPILE)

# include common make file

include $(TEMPLATEROOT)/Makefile.common
